import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { ScrollArea } from "@/components/ui/scroll-area";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header className="h-12 flex items-center justify-center bg-black text-white">
					<h1 className="text-2xl font-black">Refeel Chronicle</h1>
				</header>
				<ScrollArea className="h-[calc(100vh-48px)] p-2">{children}</ScrollArea>
			</body>
		</html>
	);
}
